### ISSUE TITLE
Crash after deallocating network default client

### ISSUE THREAD

**Issue by arkadysmirnov66** [elegion/ios-Flamingo#15]
steps to reproduce:
1. init network client 
2. send request 
3. deallocate client until response aren't receiving 
4. get crash on receiving response.

**Comment by Aranoledur** [comment]
Fixed here
https://github.com/elegion/ios-Flamingo/pull/14/commits/f2ff48e91cc95ea90740bd0078cba80794c658b4

**Comment by Aranoledur** [comment]
Пофикшено
